export const KP_SCHEDULES = [
  { month: 'Januari', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 Oktober - 31 Oktober' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 November - 15 November' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 November - 30 November' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 November - 10 Desember' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 November - 15 Desember' },
  ]},
  { month: 'Februari', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 November - 30 November' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 Desember - 15 Desember' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 Desember - 31 Desember' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 Desember - 10 Januari' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 Desember - 15 Januari' },
  ]},
  { month: 'Maret', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 Desember - 31 Desember' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 Januari - 15 Januari' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 Januari - 31 Januari' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 Januari - 10 Februari' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 Januari - 15 Februari' },
  ]},
  { month: 'April', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 Januari - 31 Januari' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 Februari - 15 Februari' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 Februari - 29 Februari' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 Februari - 10 Maret' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 Februari - 15 Maret' },
  ]},
  { month: 'Mei', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 Februari - 29 Februari' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 Maret - 15 Maret' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 Maret - 31 Maret' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 Maret - 10 April' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 Maret - 15 April' },
  ]},
  { month: 'Juni', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 Maret - 31 Maret' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 April - 15 April' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 April - 30 April' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 April - 10 Mei' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 April - 15 Mei' },
  ]},
  { month: 'Juli', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 April - 30 April' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 Mei - 15 Mei' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 Mei - 31 Mei' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 Mei - 10 Juni' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 Mei - 15 Juni' },
  ]},
  { month: 'Agustus', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 Mei - 31 Mei' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 Juni - 15 Juni' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 Juni - 30 Juni' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 Juni - 10 Juli' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 Juni - 15 Juli' },
  ]},
  { month: 'September', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 Juni - 30 Juni' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 Juli - 15 Juli' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 Juli - 31 Juli' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 Juli - 10 Agustus' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 Juli - 15 Agustus' },
  ]},
  { month: 'Oktober', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 Juli - 31 Juli' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 Agustus - 15 Agustus' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 Agustus - 31 Agustus' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 Agustus - 10 September' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 Agustus - 15 September' },
  ]},
  { month: 'November', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 Agustus - 31 Agustus' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 September - 15 September' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 September - 30 September' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 September - 10 Oktober' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 September - 15 Oktober' },
  ]},
  { month: 'Desember', activities: [
    { id: 1, label: 'Penyampaian surat usulan KP kepada Biro OSDM dan Input usulan KP pada Intranet Kemenperin', range: '1 September - 30 September' },
    { id: 2, label: 'Input usulan dan approval peremajaan data pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri', range: '1 Oktober - 15 Oktober' },
    { id: 3, label: 'Input usulan KP pada aplikasi SIASN Badan Standardisasi dan Kebijakan Jasa Industri oleh Admin SIASN Unit Kerja', range: '16 Oktober - 31 Oktober' },
    { id: 4, label: 'Verifikasi dan approval usulan KP pada aplikasi SIASN oleh Biro OSDM', range: '16 Oktober - 10 November' },
    { id: 5, label: 'Melengkapi usulan KP yang berstatus Berkas Tidak Sesuai oleh Admin SIASN Unit Kerja', range: '16 Oktober - 15 November' },
  ]},
];
